
package in.blogspot.ashish4java.globalweatherservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CityNotFoundException", targetNamespace = "http://GlobalWeatherService.ashish4java.blogspot.in/")
public class CityNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CityNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CityNotFoundException_Exception(String message, CityNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CityNotFoundException_Exception(String message, CityNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: in.blogspot.ashish4java.globalweatherservice.CityNotFoundException
     */
    public CityNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
